# Generated by Django 3.2.5 on 2021-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
    ]
