# Generated by Django 3.2.5 on 2021-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210912_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=1, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
